"""made changes to schema

Revision ID: 119de7aa821e
Revises: 48260be2b945
Create Date: 2026-06-12 15:48:45.783861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119de7aa821e'
down_revision: Union[str, Sequence[str], None] = '48260be2b945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_column('password_reset_tokens', 'updated_at')
    # ### end Alembic commands ###
