"""add_transcript_path_to_consultations

Revision ID: 520ca4ffa626
Revises: 941800c0a29b
Create Date: 2026-08-21 19:01:02.240343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520ca4ffa626'
down_revision: Union[str, Sequence[str], None] = '941800c0a29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('transcript_path', sa.String(), nullable=True))
    op.alter_column('consultations', 'current_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'current_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('consultations', 'transcript_path')
    # ### end Alembic commands ###
