"""added current_stage to consultation

Revision ID: 5442b2c4558d
Revises: a7dc90feb89e
Create Date: 2026-06-16 20:09:14.089058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5442b2c4558d'
down_revision: Union[str, Sequence[str], None] = 'a7dc90feb89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('current_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'current_stage')
    # ### end Alembic commands ###
