"""addded duration to appointment model

Revision ID: 941800c0a29b
Revises: 2bc6d13d6fe3
Create Date: 2026-07-16 14:47:01.292359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941800c0a29b'
down_revision: Union[str, Sequence[str], None] = '2bc6d13d6fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_duration_minutes'), 'appointments', ['duration_minutes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_duration_minutes'), table_name='appointments')
    op.drop_column('appointments', 'duration_minutes')
    # ### end Alembic commands ###
