"""added uuids and restrict deletions in models

Revision ID: a7dc90feb89e
Revises: 20609b7c7561
Create Date: 2026-06-14 16:07:46.932669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dc90feb89e'
down_revision: Union[str, Sequence[str], None] = '20609b7c7561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('consultations_patient_id_fkey'), 'consultations', type_='foreignkey')
    op.create_foreign_key(None, 'consultations', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_doctors_license_number'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    op.create_unique_constraint(None, 'doctors', ['user_id'])
    op.drop_constraint(op.f('followups_patient_id_fkey'), 'followups', type_='foreignkey')
    op.create_foreign_key(None, 'followups', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('patients', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_patients_patient_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.create_unique_constraint(None, 'patients', ['patient_number'])
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.drop_constraint(op.f('patients_user_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_reports_consultation_id'), table_name='reports')
    op.create_unique_constraint(None, 'reports', ['consultation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    op.create_index(op.f('ix_reports_consultation_id'), 'reports', ['consultation_id'], unique=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_user_id_fkey'), 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_index(op.f('ix_patients_patient_number'), 'patients', ['patient_number'], unique=True)
    op.alter_column('patients', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.create_foreign_key(op.f('followups_patient_id_fkey'), 'followups', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_index(op.f('ix_doctors_license_number'), 'doctors', ['license_number'], unique=True)
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.create_foreign_key(op.f('consultations_patient_id_fkey'), 'consultations', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
