from .appointment import Appointment
from .consultation import Consultation
from .doctor import Doctor
from .followup import Followup
from .medication import Medication
from .password_reset_token import PasswordResetToken
from .patient import Patient
from .refresh_token import RefreshToken
from .report import Report
from .user import User
